### PR TITLE
Fix failed examples tests on CI

### LINKED ISSUE #1827: Failed examples tests on CI
The following failed build need investigation: https://app.circleci.com/pipelines/github/nucypher/nucypher/4099/workflows/2d1f11bd-1d15-4116-adaa-8053138d9cee/jobs/78284

### PR DESCRIPTION
**Pull request by KPrasch**
Fixes #1827

### CODE REVIEW

**Comment by KPrasch** [comment]
Still unsure what the reason for failure is.  The exception being raised is:

```
Traceback (most recent call last):
  File "/code/examples/finnegans_wake_demo/finnegans-wake-demo.py", line 84, in <module>
    expiration=policy_end_datetime)
  File "/usr/local/lib/python3.7/site-packages/nucypher/characters/lawful.py", line 302, in grant
    handpicked_ursulas=handpicked_ursulas)
  File "/usr/local/lib/python3.7/site-packages/nucypher/policy/policies.py", line 473, in make_arrangements
    return super().make_arrangements(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/policy/policies.py", line 406, in make_arrangements
    raise self.Rejected(f'Selected Ursulas rejected too many arrangements '
nucypher.policy.policies.Rejected: Selected Ursulas rejected too many arrangements - only 0 of 3 accepted.

```

However, when I ssh into the CI server, the same test passes.

**Comment by vepkenez** [comment]
This issue is repeatable about 90% of the time locally by running
`./scripts/circle/run_finnegans_wake_demo_docker-circle.sh` against master.

if the ursulas are _not_ running and you see
```
Starting circleursula1       ... done
Starting nucypher-circle-dev ... done
Starting circleursula2       ... done
Starting circleursula3       ... done
Starting circleursula4       ... done
```
then it fails 100% of the time.
with either this:
```
nucypher.policy.policies.Rejected: Selected Ursulas rejected too many arrangements - only 2 of 3 accepted.
```

or this error:
```
Found 0 for this Capsule (Capsule:79993d71c8df409).
Ursula ((Ursula)⇀DodgerBlue Sagittarius Lavender Crossbones↽ (0x381a5c8cB12D73884690547E95B792db12957602)) seems to be down while trying to complete WorkOrder: WorkOrder for hrac 857a3f: (capsules: [Capsule:79993d71c8df409]) for Ursula: b'020e90'
Ursula ((Ursula)⇀Salmon Beverage LightPink King↽ (0xcB458D1a1F50448921F278BAeA848fC2150d78cb)) seems to be down while trying to complete WorkOrder: WorkOrder for hrac 81f2c0: (capsules: [Capsule:79993d71c8df409]) for Ursula: b'02bd3f'
Traceback (most recent call last):
  File "/code/examples/finnegans_wake_demo/finnegans-wake-demo.py", line 148, in <module>
    label=label)
  File "/usr/local/lib/python3.7/site-packages/nucypher/characters/lawful.py", line 825, in retrieve
    "Unable to reach m Ursulas.  See the logs for which Ursulas are down or noncompliant.")
nucypher.characters.lawful.NotEnoughUrsulas: Unable to reach m Ursulas.  See the logs for which Ursulas are down or noncompliant.
```
at this point, because the script fails, it doesn't stop the ursulas as it would after a successful run.
If you run it again, after a fail, with the ursulas already running, everything works.
This may be why logging into the container via ssh and running the script doesn't reproduce the issue consistently.

**Comment by vepkenez** [comment]
Removing the sleep for learning loop fixed this.  I am not sure why but it seems like with the learning loop optimizations recently, we no longer need it anyway. 

I was also able to get it consistently working with a sleep time of 60 seconds... 30 and 45 didn't work.

I assume this is because of some interaction with the new availability check mechanics and a fleet of ursulas all started simultaneously or something like that.  Maybe you @KPrasch might have more insight about possible causes.

**Comment by KPrasch** [comment]
Okay - Squashed and rebased with deprecated sleep in CI scripts.

**Comment by vepkenez** [comment]
@KPrasch actually some waiting is necessary on the heartbeat demo, it will fail because it hasn't even written config files yet etc.

File: scripts/circle/run_heartbeat_demo_docker-circle.sh [hunk 1]
```diff
@@ -8,8 +8,8 @@ echo "Starting Up Heartbeat Demo Test..."
 
 # run some ursulas
 docker-compose up -d
-echo "Wait for Ursula learning to occur"
-sleep 30
+
+echo "wait a few seconds for initting and learning"
```
Comment (derekpierre) [inline scripts/circle/run_heartbeat_demo_docker-circle.sh:12]: Is this message needed since we are no longer doing a `sleep`? as opposed to 

```suggestion
echo "running heartbeat demo"
```

Comment (vepkenez) [reply scripts/circle/run_heartbeat_demo_docker-circle.sh]: 👍
